preprocessorDirective    ::= defineDirective
                           | ifStatementDirective
                           | errorDirective
                           | importDirective
                           | includeDirective
                           | undefDirective
                           | usingDirective

defineDirective          ::= '#define' identifier expression
                           | '#define' identifier '(' arguments? ')' expression

ifStatementDirective     ::= (ifDirective | ifdefDirective | ifndefDirective) elifDirective* elseDirective? endifDirective
ifDirective              ::= '#if' expression lineTerminator unicode lineTerminator
ifdefDirective           ::= '#ifdef' identifier lineTerminator unicode lineTerminator
ifndefDirective          ::= '#ifndef' identifier lineTerminator unicode lineTerminator
elifDirective            ::= '#elif' expression lineTerminator unicode lineTerminator
elseDirective            ::= '#else' lineTerminator unicode lineTerminator
endifDirective           ::= '#endif'

errorDirective           ::= '#error' string
importDirective          ::= '#import' string
                           | '#import' '<' unicode '>'
includeDirective         ::= '#include' string
                           | '#include' '<' unicode '>'
undefDirective           ::= '#undef' identifier
usingDirective           ::= '#using' string
